### ISSUE TITLE
[BUG REPORT] 打包单文件的修复功能可能不正确

### ISSUE THREAD

**Issue by Jenway** [SDUQD-SNA/SduNetCheckTool#6]
如果尝试使用打包的单文件，检测功能是正常的，但修复功能似乎会出现一个奇怪的现象 : 它会一遍显示修复失败，一边自动打开系统的代理设置中的 `手动代理设置`

我尝试了多个版本，从最新的构建到由1.3 版本打包的单文件都存在这个问题

我认为这 **可能** 是一个严重的 BUG

![image](https://github.com/SDUQD-SNA/SduNetCheckTool/assets/63341978/fc69a0a9-eb95-4735-9e40-d4cdec4fde60)

**Comment by Jenway** [comment]
经过尝试我似乎定位到了问题所在的地方，如果在打包时不把 sysproxy.exe 打包进去，就不会出现这个问题，但是我还是不清楚问题产生的原因，此外，谁能给我讲一下 sysproxy.exe 的作用原理吗？

**Comment by Jenway** [comment]
原来 sysproxy.exe 是 [shadowsocks](https://github.com/shadowsocks/sysproxy) 里面的...

我修改了一下源码，让它生成 dll 然后调用，这样似乎就可以解决问题。

不过这里要确保编译的 dll 和 程序的位数是一样的，比如都是 64 位或者都是 32 位

值得一提的是，这可能也暗示了为什么这个 BUG 会产生

参见[这个链接](https://www.softwareprotection.info/2019/02/files-virtualization-and-portable-applications/)

> Another executable files can also be added to Virtual Box, it’s OK. But Virtual Box will be able to run the virtual exe file only if architectures of main executable and virtual are the same, i.e. both files are 32 bit or 64 bit executables. If main executable is 32 bit file, but virtual is 64 bit, then Virtual Box will be unable to start such virtual exe.

我猜测原本的sysproxy.exe 是32位程序，而编译产出的程序是 64 位，因而会产生问题

@Forgot-Dream 我们要限定我们的程序产出是64位的吗？如果是那样的话，直接编译一个64版本的dll来调用就好，我已经差不多写好了一个类似的方法，也已经编译好了 dll，代码参见[我 fork 的仓库](https://github.com/Jenway/sysproxy)

或者为了兼容性考虑，可以加一个运行判断，只不过这样要放两个 dll

**Comment by Forgot-Dream** [comment]
我可能更加倾向于使用纯C#的解决方案，如 https://github.com/2dust/v2rayN/blob/master/v2rayN/v2rayN/Handler/ProxySetting.cs
